main.out:main.o LOperate.h LOperate.o Linear.h 
	gcc -std=c99 -g main.o LOperate.o -o main.out
LOperate.h:LOperate.o Linear.h

InitList.o:InitList.c
	gcc -c InitList.c

LOperate.o:LOperate.c
	gcc -c LOperate.c

